### ISSUE TITLE
新创建的任务，怎么添加welcome标签

### ISSUE THREAD

**Issue by bubbleatgit** [fleeto/issueflow#4]
![image](https://user-images.githubusercontent.com/7858776/54116754-6aa4a100-442a-11e9-9f2a-cbebe6bfa606.png)
按文档所述，新创建任务会自动添加名为 `weclome` 的lables。目前我配置的机器人不会添加该标签，请教下是否有其他需要配置的地方？

https://github.com/gitlab-ce-zher/gitlab-docs-official-translation/issues

**Comment by fleeto** [comment]
还有 flaskapp/gcp 的打包，用来挂 webhook 的， README 里面也有说。那个是处理 issue 相关指令的

**Comment by bubbleatgit** [comment]
找到问题了，flask这个webhook不会处理在接入webhook之前已经创建好的issue。是因为我开始只部署了机器人儿，没有搞webhook，所以新issue没有welcome的标签。

**Comment by bubbleatgit** [comment]
感谢大佬的程序

**Comment by fleeto** [comment]
最近有点忙，但是正在筹备一个比较大的升级，敬请期待：）
